# VuMoS docker compose file

version: "3.8"

networks:
    vumos:

volumes:
    postgres-data:

services:
    postgres:
        build:
            context: ${CONTEXT_PATH}/postgres
            dockerfile: Dockerfile
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - vumos

    alembic:
        build:
            context: ${CONTEXT_PATH}/alembic
            dockerfile: Dockerfile
        environment:
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_NAME=${DB_NAME}
        volumes:
            - ${SRC_PATH}/alembic:/home/alembic/alembic
            - ${SRC_PATH}/commons:/home/alembic/commons
            - ${CONTEXT_PATH}/alembic/docker-entrypoint.sh:/home/alembic/docker-entrypoint.sh
        links: 
            - postgres
        depends_on:
            - postgres
        networks:
            - vumos
